services:
  database:
    build:
      context: infra/dev
    hostname: "pgtimegis"
    environment:
      - POSTGRES_PASSWORD="password"
    tty: true
    ports:
      - 5432:5432

  api:
    build:
      context: src
    hostname: "map-storage-api"
    tty: true
    ports:
      - 8080:8080
      